:PROPERTIES:
:ID:       60e8f82d-2017-42c1-a619-a9629d720385
:END:
#+title:Occult Board@channel
#+filetags: :SteinsGate:ChatLog:
* After-thoughts
- web address: anchorage.attoch.net/occult
* Recent threads concerning  =John Titor=  (dtd 7/29 Evening)
** =John Titor= @f8VuYnoyWU:2010/07/29(Thu) 15:04:29
#+BEGIN_QUOTE
ID: 4Co5c6io0
 I see that everyone would like to know more about my time machine.
 I'm happy to explain.
 Just so you know, it's impossible to reproduce it with current technology.
 Certain critical components won't exist until SERN invents them in 2034.
 Time travel works by altering gravity.
 Basically, you can think of it as using the twin paradox.
 But that isn't enough to reverse the time.
#+END_QUOTE
*** ~Anonymous~
#+BEGIN_QUOTE
 ID: b6ohLRKPO
 	 Still here faker?
 	 ur annoying. Go away.
 ID: K3Vie+Ed0
 	 So, your power is gravity control? Not bad, but still not enough for rop-tier power levels.
 ID: twA9im/8O
 	 The twin paradox? Is that like Urashima effect?
 	 That's just slowing time down, not reversing it.
 ID: XCOl4WFG0
 	 Who gives a shit about time machine?
 	 Give me stock price!
#+END_QUOTE
** Hououin Kyouma: 2010/07/29(Thu) 15:06:29
#+BEGIN_QUOTE
 ID: 1Kz7Z7Sn0
 #229
 It uses Tipler Cylinders and Kerr Black Holes, doesn't it?
 Just like you said 10 years ago!
 And your time machine is a *1970s Chevi*!
 I know all of it!
#+END_QUOTE
*** ~Anonymous~
#+BEGIN_QUOTE
 ID: sjCZ8ysE0
 	#229 Oh god shut the fuck up you disgusting chuuni scum
 ID: Lqjl70lsO
 	#232 The twin paradox and the Urashima effect are different things, duh.
 ID: 2xDTmiuLO
 	time travel lol
 	john titor lol
 ID: 5rtMan8S0
 	 #234
 	 A Chevi's an American car, right?
 	 I'd rather go German with a BMW lol
#+END_QUOTE
** ~KuriGohan and Kamehameha~  :2010/07/29(Thu) 15:19:38
#+BEGIN_QUOTE
 ID:0WM1H5LT0
 #234
 By Tipler cylinders, are you refering to the Tipler machine?
 lolwut?
 A Tipler cylinder would have to be 10 km in diameter, 1000km long, have mass equal to the sun, and revolve 2500 times per second to become a time machine lol
 How do you fit that onto a Chevi?
 Even if you could, a Tiple machine can't travel back in time than the moment of creation.
 Enough of your delusion.
 @channel is not your bog
 I want to hear from Titor.
#+END_QUOTE
** =John Titor= @f8VuYnoyWU:2010/07/29(Thu) 15:20:29
#+BEGIN_QUOTE
 ID: 4Co5c6io0
 This is a surprise.
 Does this mean people of this age already know about my time machine?
 Did you really encounter me ten years ago?
 If so, then that must have been on another world line.
 I, at least, have not gone to the year 2000.
 In any case, the important point is that a rotating black hole has the same effect as a Tipler cylinder.
 You can learn more about Kerr black holes by studying the **Penrose diagram** or **Tipler's calculations**.
 My time machine works by generating a pair of Kerr black holes.
#+END_QUOTE
*** ~Anonymous~
#+BEGIN_QUOTE
 ID: g0EVX39A0
 	In Japanese plz
 ID: gigiR1Hh0
 	Titor came 10 years ago? Source?
 ID: K483z8/c0
 	Wtf are Kerr black hole?
 	Explain using boobies oh erotic one!
 ID: odGzF8qBO
 	I will pay 1000 yen to ride your time machine.
 	Not a yen more!
 ID: 0cc0yP/Q0
 	 Hey ID#K483z8/c0
 	 Source is Houou-san's delusions lol
 	 Real deal
#+END_QUOTE
** ~KuriGohan and Kamehameha~ :2010/07/29(Thu) 15:25:34
#+BEGIN_QUOTE
 ID: 0WM1H5LT0
 He didn't deny it? LOOOOOOOOOOOOOOL
 All abroad Hououin's crazy train, prepare for a trainwreck!
 Kerr black hole time trave is theoretically possible, but
 	1. How do you get black holes to spin? Don't tell me you wait until you find one spinning naturally. That's ridiculous.
 	2. How do you pass through the singularity?
 There's no way a Chevi can withstand the pressure.
#+END_QUOTE
*** ~Anonymous~
#+BEGIN_QUOTE
 ID: jPm+uqabO
 Why the short explanations, John? You stupid? Wanna die?
 ID: ZPjtoV5f0
 Still no stock prices? *crash*
#+END_QUOTE
** Hououin Kyouma :2010/07/29(Thu) 15:26:08
#+BEGIN_QUOTE
 ID: 1Kz7Z7Sn0
 This isn't a delusion.
 I know for a fact that Titor posted ten years ago.
 There's even a book about it. Search the used book stores in you don't believe me.
 His Chevi has a gravity distortion unit.
 That's what he said 10 years ago.
#+END_QUOTE
** JOHN TITOR@f6VuYnoyWU:2010/07/29(Thu) 15:37:55
#+BEGIN_QUOTE
 ID: 4Co5c6io0
 Yes, it does have a gravity distortion unit.
 My time machine is not perfect. It was built by a third party who reverse engineered SERN's design.
 The gravity distortion unit is a little unstable.
 First, the unit produces a micro singularity, then injects electrons to induce rapid rotation.
 This generates a local gravity sine wave.
 As the time machine passes through the singularity, the gravity distortion unit regulates the pressure to ensure safe passage.
 I'm not a specialist, so I cannot explain the mechanics any further.
 Let me just say that Kerr black holes can be manufactured.
 I assume everyone's aware of SERN's current experiments with black hole creation.
#+END_QUOTE
*** ~Anonymous~
#+BEGIN_QUOTE
 ID: lofLpstvO
 	tl;dr STFU!!1!1!
 ID: C7QwgBSS0
 	Unstable? Sounds dangerous.
 ID: BrrQolR00
 	Oh fuck!
 	Titor's black holes are gonna swallow the Earth!
 	He is not just a mass murderer! He's trying to wipe out the entire human race!
 	Find his parent before it's too late!
#+END_QUOTE
** ~KuriGohan and Kamehameha~:2010/07/29(Thu) 15:40:27
#+BEGIN_QUOTE
 ID:0WM1H5LT0
 It's not that you won't explain, it's that you can't, lol.
 How do you set the destination? The Earth is constantly moving, or did you not know that?
 By the way, I propose the Titor=Hououin theory lol.
#+END_QUOTE
** JOHN TITOR@f8VuYnoyWU:2010/07/29 (Thu) 16:01:20
#+BEGIN_QUOTE
 ID:4Co5c6io0
 I set the destination with the VGL system.
 That is "Variable Gravity Lock."
 It functions by reading the local gravity of the destination and locking the Tipler sine wave onto that location.
 By locking onto Earth's gravity, it ensures that I don't end up floating in space.
 It uses 4 caesium clocks to make the calculations, so the margin of error is negligible.
#+END_QUOTE
*** ~Anonymous~
#+BEGIN_QUOTE
 ID: OSrrA5ca0
 	Hououin needs to shut up lol
 	I never heard of any Titor from 10 years ago lol
 ID: YKFYUVjGO
 	So the universe is deep in Titor's shit.
#+END_QUOTE
** =Hououin Kyouama=: 2010/07/29 (Thu) 16:04:15
#+BEGIN_QUOTE
 ID:1Kz7Z7Sn0
 The same information was in the Titor book.
 All you've done is post a ten-year-old copypasta.
 Anyone could do that. How do I know you're the real Titor.
#+END_QUOTE
*** ~Anonymous~
#+BEGIN_QUOTE
 ID:yiNxM5tq0
 John-tan's so moe. Mai waifu
 I recognize different opinions.
#+END_QUOTE
** ~KuriGohan and Kamehameha~: 2010/07/29 (Thu) 16:05:41
#+BEGIN_QUOTE
 ID: 0WM1H5LT0
 I'm feeling more and more disappointed...
 Still nothing concrete.
 Nice try, I guess, but I won't be fooled.
#+END_QUOTE
