:PROPERTIES:
:ID:       736cfa99-72da-4fbe-83f9-4fe95c66ea87
:END:
#+title:Luka
#+filetags: :SteinsGate:Character:
* After-thoughts


* Detail
+ Shrime maiden named Urushibara Luka.
+ In the words of [[id:cf5e0883-ac65-423b-8671-457f1a6c99b2][Rintaro]], "A stunning example of feminine charm and grace. Lips delicate like cherry blossoms in bloom. The essence of Japanese beauty. The chief priest's son. That's right, 'son'. Lovely in every way... but he's a guy." {a distasteful queer joke?}
+ Rintaro's continue his crusade on this cross-dressing person:
  He bows his head.
  The voice of a girl. The mannerisms of girl.
  More feminine than any girl I know.
  *But he's a guy.*
  Taller than Mayuri. Yet oh so slender.
  *But he's a guy*.
  Looks stunning in miko robes.
  *But he's a guy*.
  Holding a bamboo broom. Apparently in the middle of cleaning.
  *But he's a guy*.
  It's almost evening, yet still hot as hell outside.
  *But he's a guy.*
  Damn cicadas won't shut up.
  *But he's a guy*.
  #+BEGIN_COMMENT
  Looks like he really can't shake away the thought the Luka is a guy. At least they're friend so maybe Luka don't get offended by straight as a rod head of Rintaro.
  #+END_COMMENT
+ Rintaro calls him *Lukoka*. {Could it be to shake away the gender neutral ambiguity of Luka as a name and firmly make him a male?} They met first time when Rintaro rescued Luka while he was aggresively getting hounded by some photographers in Akiba's Pedestrian Heaven.
+ It just so happens that Luka and  [[id:ec77fd83-5cf4-484e-a1f3-890f1b351c08][Mayuri]] are also classmates.
+ Rintaro has given him a toy sword from BladeWorks named **Demon Sword Samidere** so that he can learn to control his power. By Rinataro's demand, he has to master the Seishin Zanma school of swordsmanship so that Luka can prevent the dark flame inside him from consuming his soul.
+ Luka and Rintaro shares some secret code ***El Psy Kongroo***, which is something made up by Rintaro. Their relationship feels very much like that of master and apprentice.
+ By Rintaro's assessment Lukako is very obedient eager-minded and hardworking. His weakness can be being too shy or sometime not catching on to something too quickly.
+ 17 years old.
