:PROPERTIES:
:ID:       14a28c3a-1829-40a3-938f-45a4b07aec12
:END:
#+title:Moeka
#+filetags: :SteinsGate:Character:
* After-thoughts


* Details
+ Full name: Kiryu Moeka
+ 20 year old freelance editor
+ Works part time at Arc Rewrite (by her own claim)
+ When questioned by [[id:cf5e0883-ac65-423b-8671-457f1a6c99b2][Rintaro]], she starts babbling about some urban legend of phantom retro PC located in Akihabara. In particular she is looking for an [[id:bc424e69-a45f-4083-a19a-b9bb3e0a910f][IBN 5100]]. {It's the same PC that John Titor was looking for when he time travelled first time 10 years ago i.e. in the year 2000. *{refer: highlights, chapter 1}*
+ Rintaro thinks she is an esper (one with Extra Sensory Perception (ESP)) with the power of Shining Finger! Her magical thumb types at the speed of 255 characters per minute. He saves her name as 'Shining Finger' on his phone.
+ Later, she assures Rintaro that she isn't going to use his picture for any malicious reason or post it on forums without consent. In fact, she was there near Radi-Kan to snap some test shots of nearby area and the crashed satellite in particular. Even if Rintaro hadn't asked her to delete his photo, she would have done so anyways.
