:PROPERTIES:
:ID:       65e12ac9-bd4e-414a-8bdb-93ba630a4a33
:END:
#+title:Chapter-3
#+filetags: :SteinsGate:ButterflyEffectsDivergence:
* After-thoughts
* Pressing Questions
# Butterfly Effect's Divergence
*  Location:   [[id:e3ad92cc-8fe8-40fb-a7b2-b65e4fbf9c2f][Future Gadget Laboratory]]
#+BEGIN_CENTER
 dtd 08/02 (MON) 02:00 (source: Rintaro's narration)
#+END_CENTER
** Everyone is in a state of shock.  [[id:1d9e7331-84b9-4ba2-9304-f370b3c5dfe1][Kurisu]] says the obivious despite everyone's disbelief that it's highly likely that  [[id:ae74f4f4-9ed7-4459-b8d6-aa5b43acaf61][SERN]] has succeeded in creating the time machine. She points to a photgraph in the newspaper which shows gelified man having an odd tattoo on his shoulder. The tattoo marks 'SERN' followed by some sort of serial number on the body.
** When questioned by [[id:cf5e0883-ac65-423b-8671-457f1a6c99b2][Rintaro]] about number of such reports in existence, Daru replies that there are at least 14 people in total. Following Rintaro's request, Daru and Kurisu start opening and translating other [[id:35af92d5-7fdb-4d30-9f55-00c081bcfbf7][Jellyman's Report.]]
** Rintaro has had enough of these grim reports. Kurisu questions, if the sites of Jellyman discoveries, being all over the world in a seemingly random manner, has any deductible meaning behind it. When asked about the mentions of supergravity and [[id:f9730efd-b266-4049-8298-eae48d5da1aa][Kerr black holes]] as possible cause in those reports, Kurisu explains that due to infinite compression by supergravity, the subject could not endure passage through the Kerr black hole's singularity.
** Rintaro recalls that John Titor has mentioned something about his time machine functioning on Kerr's blackhole. Titor also said that SERN will finish their time machine in 2034. Titor himself claimed to be a visitor from the year 2036.
** Kurisu's practical mind still can't comprehend the existence of Kerr black hole. By her understanding, Kerr black hole was meant to be nothing more than a theoratical construct. Instead of speculations, Daru suggests to look further into other documents related to time travel on SERN's database. Rintaro feels a little conflicted about going further deep into this. The fear of future consequences due to these actions and his irresistible curiosity for the possibility of time travel becoming a reality are at war against each other.
** Curiosity overshadows the fear as Daru finds a Z Program related document detailing the time travel theory. Kurisu is feeling a little sus about SERN's security being this weak. Once Kurisu goes over the document, she mutters something about this being same as [[id:2ca21175-8217-4ce0-8ecf-4e374aa9a144][Titor's Theory]]. This theory details how Kerr black hole can be used to fascilitate time travel. It's astonishing that SERN is able to bring the functionality of 27 kms long LHC to a travel size equipment in just 25 odd years.
** Kurisu is curious about the mechanism by which SERN is injecting electrons in LHC to accelerate proton particles. In the cross-sectional image of LHC, there is a strange equipment installed at the proton collision site. They're calling it a '*LIFTER*'. "Could it be an Ionocraft?", Kurisu makes a guess based on google search results. Essentially, an ionocraft lifts or suspends electrodes in a charged/ionised surrounding atmosphere.
** It seems SERN are using Iconocraft/LIFTER as means to impart angular momentum to spinning protons and reach a threshold where the outer event horizon expands into an ergosphere resulting is creation of the naked singularity. It seems SERN is facing issue in creating the naked singularity. Since the ergosphere is not formed, the subjects are getting crushed and becoming fractalized by the tremendous gravity of micro-singularity. At the end of the day, this is nothing more than a hypothesis. By Kurisu's account, it would take months to prove this.
** Assuming John Titor's words to be true, then SERN would need another 24 years to sort out this issue. Our mad genius has a brilliant idea that if they complete the PhoneWave first, they would totally outwit SERN. Kurisu brings Rintaro back to reality by bringing up the issue of lack of funding or the equipment {not to forget the manpower}.
** Kurisu claims that SERN also hasn't figured out how to set the subject's destination in time or space. Both spatial and temporal randomness in the appearance of Jellyman corpses justify this claim.
** Titor had seemingly said that he used a '*variable gravity lock system*'. He could use that to lock onto the Earth's gravity and make assured landing somewhere on the earth. Kurisu highlight the vagueness in Titor's explaination as in he didn't explain how such a device would work.
** Daru chimes in with a question that if one is spatially immobile inside the event horizon, wouldn't that mean they will be at same position whenever they arrive? This won't be the case as the Universe is not stationary as observed from an inertial frame of reference. Kurisu adds that earth is always moving about it's own axis, around sun. Not to forget that the milkyway galaxy containing earth is also spinning like a giant whirlpool. Roughly speaking, the earth is moving at an estimated pace of 50 million kms a day wrt inertial frame of reference. In summary, setting the destination would require insane calculations even if you travel 1 second into past. Even years long computation performed with supercomputer would baerly arrive at a solution that can bring the time traveller to same locaton.
** A mail from Faris pauses the mindblowing conversation for the time being,
**** [!info] frm: Faris dtd: 08/02 3:20
**** sub: Phantasm is the cat's meow
**** Have you bought *Phantasm*'s debut single, nya? It's the *theme song* for 'RaiNet Kakeru', so it's really popular. Faris bought 5 copies, nya. It's my duty as a RaiNetter! Anyway, there's an *important secret* hidden in Phantasm's songs. The key to unlocking it is... Oops, the bell is ringing, nya.Looks like someone's here. Better see who it is.
***** ***Rintaro's reply***: <Keyword: important secret* I'm aware. They are said to contain directions to the sanctuary, as well as prophecies regarding the end of the world. Isn't that right?
** Rintaro proposes a fabulous idea that they should meet [[id:6182233e-8233-42f7-83ff-fc8d00279b9a][John-Titor]] and ask him to borrow his variable gravity system. Kurisu gives him a sarcastic go ahead signal and goes back to reading the SERN document.
** Dawn is approaching. Daru is fast asleep on the sofa. The noise of snoring, due to Daru's sleep apnea, is echoing in the room. Rintaro is shocked by Kurisu's level of concentration. Rintaro decides not to disturb her and instead chooses to watch some TV. News channels are still covering the satellite crash at the Radi-Kan. It's been 5 days since the crash. People from different part of Japan are still flocking to the site of crash. The news channel reports on an interview from Michael Byrne, NASA's spokesman. He states that no satellite has crashed in Japan, and that the crashed object is not even a satellite. As the news of the satellite being under investigation with date of removal from the crash site still up in the air is being reported, a mail from  [[id:caf8e76b-d0be-4905-b4f4-1c704b70ff34][Amane]], interrupts Rintaro's thought.
**** [!info] frm: Part-Time Warrior dtd: 08/02 11:39
**** sub: Hungry
**** I'm so hungry! I had to skip breakfast again today. I don't have much money on hand. Are there any good places to find *insects or weeds* around here? I can get by using my *survival skills* if I have to.
***** ***Rintaro's reply***: < survival skills * What kind of childhood did you have?
** As Rintaro is done sending the reply, Mayuri enters the apartment in her usual cheerful mood. Rintaro attempts to clear the gloomy atmosphere by announcing a roundtable conference for all lab members.
** First order of the business, they have to inform mayuri about everthing that has happened so far. The gist of it, according to Rintaro, is:
>SERN making a time machine... Jellyman reports... Men in black might be coming to erase us.
** Mayuri still has doubts about Rintaro's path. Kurisu is fully onboard as SERN bigger of the two evil. Rintaro proclaims that Ragnarok is unavoidable as the final battle with SERN nears. Once the lofty monologue is over, he 'orders' Kurisu to lay it bare, whatever she has learned from SERN documents.
** Kurisu reports that SERN is facing two problems with time travel. The problem lies with,
     1. electron injection device, also known as a *LIFTER*,
     2. specifying exact physical location for subject's appearance after time travel.
** Kurisu adds that those 14 found Jellymen were lucky in a way that their body stayed on the habitated part of earth. The truth is that there has been more than 100 human experiments performed since 2001.
** When questioned by Rintaro about any findings that can help understand PhoneWave's behaviour, Kurisu replies that one can call *the LHC*, ***the world's largest microwave***. Rintaro makes an ahaha comment, "**Of course, PhoneWave is a miniature LHC!**"
** Much to the surprise of Rintaro, Kurisu agrees with his remark. She adds that there are many fine details which appears quite vague about the PhoneWave. For example, Why do the same phenomenon that occur in SERN's time machine also happens in the tiny microwave? Unlike LHC, this thing wasn't made for time travel.
** Rintaro argues that Mayuri's banana must be reaching the Kerr black hole's ring sigularity to end up like gelbana, similar to Jellyman phenomenon. Kurisu adds that they still haven't figured out how the electric discharge phenomenon occur or what are the conditions required to cause it.
**
