:PROPERTIES:
:ID:       0ad513d9-f1ba-4a26-aaa3-e52e8bc0c2dc
:END:
#+title:Chat log no 3
#+filetags: :SteinsGate:ChatLog:
* After-thoughts
* dtd 7/30 from 17:36 to 17:44
** =John Titor=
#+BEGIN_QUOTE
The Everett-Wheeler model is correct. Please look it up to learn more. It seems you're all still clinging to preconceived notions of time. Time does not simply run from past to future like a car on a one-way street.
To be more specific, the laws of causality do not allow contradictions to occur. If the result of an event - the effect - is changed, the event itself - the cause - also changes to prevent a paradox.
That's why there are so few people who can observe changes in divergence. (Divergence being the world line's percent difference from the standard.)
#+END_QUOTE
** Anonymous
#+BEGIN_QUOTE
1. die troll...you claim to be a time traveler without any proof
2. stcok trend plz...i'm counting on you mr. time traveler
#+END_QUOTE
** /KuriGohan and Kamehameha/
#+BEGIN_QUOTE
If you can't observe changes in divergence, then how can you possible measure it? Oh, I know! Your time machine has a magical device that measures it for you lolololol
Oh, and you still haven't explained how a research institute conquered the world. Details plox
#+END_QUOTE
** Anonymous
#+BEGIN_QUOTE
1. Oh noes! Humanity is doomed! whathassciencedone.jpg
2. lol, newbs responding seriously to troll thread... This Titor guy is a shitty troll
#+END_QUOTE
** ~Hououin Kyouma~
#+BEGIN_QUOTE
Don't you people have anything to offer besides insults? How about contributing to the discussion, plebeian scum!
If you assume that time doesn't flow in straight line, then the idea of time travel is much easier to swallow.
In such a secenario, a time machine traveling to the past doesn't need to fight the flow of time!
I say Titor's point have merit.
By the way, Titor, I'd like to know more about SERN. What can you tell us about their current activities?
#+END_QUOTE
** Anonymous
#+BEGIN_QUOTE
1. Tell me which horse wins the next emperor's cup... I'll bet my entire life savings
2. Everett-Wheeler model = many-worlds interpretation... Basically, that means parallel worlds.
3. What's with all the stupid nametags? This  ~Hououin Kyouma~ is more annoying than Titor.
4. You call yourself  =John Titor= but you're fluent ijn Japanese... Writing in English would atleast make it seem more realistic... You can't do english, can you?
5. Can I ask you a favor, Titor-san?... My mom died last year in the Shibuya Earthquake. If I stop my mom from leaving home, then I can undo her death.... So please, let me lend your time machine!
#+END_QUOTE
** /KuriGohan and Kamehameha/
#+BEGIN_QUOTE
@ Kyouma you're gonna believe this time traveler (lol) without proof? Are you an idiot?
#+END_QUOTE
* dtd 30/7 from 18:09 to
** =John Titor=
#+BEGIN_QUOTE
No one seems particularly interested in what I said about time not flowing in a single direction. That's proof that your preconceptions are deeply ingrained. Honestly, it bothers me that you simply accept that as the truth. I'm starting to understand why SERN was able to take over so easily.
Whenever a major event causes divergence to change, the timeline is reconstructed to prevent paradoxes from occuring. For example, let's say that a major event causes this world line to diverge into a new world line, let's call it world line B.
On world line B, I'm afraid to say, @channel never existed. As the timeline is reconstructed, all of your memories of reading and posting on @channel will disappear, to be replaced by memories you doing something else.
In other words, by changing the present, you change the past.
I wrote about SERN yesterday. The only other thing I can say is that you must not believe their lies. They have already succeeded at creating micro black holes.
#+END_QUOTE
** ~Hououin Kyouma~
#+BEGIN_QUOTE
@/KuriGohan and Kamehameha/
I desire only to quench my intellectual thirst. Unlike you close-minded fools, I will reserve judgement until after I've heard what Titor has to say.
And then, I will make contact with Titor and acquire his time machine for myself. The great mad scientist,  ~Hououin Kyouma~, will have the last laugh! Suck it sleazebags!
#+END_QUOTE
** Anonymous
#+BEGIN_QUOTE
1. Tell me stock prices or fucking die...I won't believe until you tell me!
#+END_QUOTE
** /KuriGohan and Kamehameha/
#+BEGIN_QUOTE
That's not reconstructing the world, you idiot, that's altering people's memories. Who the hell can alter the memories of nearly 6.7 billion people?
Do you even realize how stupid that sounds?
I think I would have noticed if someone went and screwed with my brain. And what does any of that have to do with the many world interpretation? Do some research lol.
"micro black holes"....lololololol
#+END_QUOTE
** Anonymous
#+BEGIN_QUOTE
1. Wait, the future is a wasteland? That means I can be a road warrior and ride a mod buggy, right!? I'ma go get me a mohawk! Anyone know where I can buy spiked shoulder pads?
2. I checked SERN's homepage. It says they'ev been experimenting sice 2009. Can they rly make black holes?
3. What the hell's gonna happen?
4. Does Titor have a mohawk? God, that;s fucking moe!
5. Are you implying our brain create the world? Are you saying the universe is a giant tree and we're the branches or something? That's some Eva-level bullshit right there. Go back to 2036!
#+END_QUOTE
** =John Titor=
#+BEGIN_QUOTE
@ //KuriGohan and Kamehameha//
Is this how you reply to a specific person? Thank you for showing me.
Reconstruction of timeline and alteration of people's memories... I think they're essentially the same thing. Why are you so intent on saying they're different? **With a few exception, nobody can keep their memories across world lines.**
They are reconstructed along with everything else when divergence changes.
What's a road warrior?
#+END_QUOTE
