:PROPERTIES:
:ID:       89bbbf23-d746-4638-a351-d9ab272293d3
:END:
#+title:Archived John Titor's chat log
#+filetags: :SteinsGate:ChatLog:
* dtd 28/07/2010
** #294 Name: =John Titor= :2010/07/28(Wed) 20:11:45
#+begin_quote
I don't expect you to believe that I came from the year 2036.
I see that everyone would like to know more about my time machine.
Time travel technology was developed by SERN.
They completed the first time machine in 2034.
#+end_quote
** #295 Name: ~Anonymous~ :2010/07/28(Wed) 20:12:21
#+begin_quote
time traveller lol
john titor lol
#+end_quote
** #296 Name: ~KuriGohan and Kamehameha~ :2010/07/28(Wed) 20:15:08
#+begin_quote
moar details on the time machine
#+end_quote
** #297 Name: ~Anonymous~ :2010/07/28(Wed) 20:15:54
#+BEGIN_QUOTE
Do you sell time machines?
How much do they cost?
I've got about a hundred million yen saved.
Can you send me one?
#+END_QUOTE
** #343 Name: =John Titor= :2010/07/28(Wed) 20:47:42
#+BEGIN_QUOTE
SERN has monopoly on time machines.
Not even the most powerful nations on the Earth can acquire one, to say nothing of private citizens.
SERN used their time machine for power. By 2036, the world has become a dystopia.
There is no war. No conflict. However, this is a false peace founded on the complete eradication of liberty.
What does "lol" mean?
#+END_QUOTE
** #344 Name: ~Anonymous~ :2010/07/28(Wed) 20:48:19
#+BEGIN_QUOTE
Why did you come this time?
Was the Akiba satellite crash your doing?!!1!1
#+END_QUOTE
** #345 Name: ~Anonymous~ :2010/07/28(Wed) 20:48:37
#+BEGIN_QUOTE
Wait guyz
Titor-san doesn't understand [[@channel]] lingo
Let's keep it simple, kay?
If you know what I mean
#+END_QUOTE
** #346 Name: ~Anonymous~ :2010/07/28(Wed) 20:50:00
#+BEGIN_QUOTE
Get a tripcode, asshole.
#+END_QUOTE
** #476 Name: =John Titor= :2010/07/28(Wed) 22:07:41
#+BEGIN_QUOTE
I came here to change my present. In other words, your future.
My mission is to destroy SERN's dystopia and restore freedom to the world.
This is a wonderful time you're living in. Everyone is free.
But you will lose it all in just twenty short years.
It is vitally important that you understand what the future has in store.
What is a tripcode? I might get one if you tell me what it is.
#+END_QUOTE
** #477 Name: ~Anonymous~ :2010/07/28(Wed) 22:07:52
#+BEGIN_QUOTE
You said only SERN has time machines.
You have a time machine. That must mean you're working for SERN.
Therefore, your goal can't be to destroy SERN's dystopia. You're a fraud.
QED.
#+END_QUOTE
** #478 Name: ~Anonymous~ :2010/07/28(Wed) 22:08:20
#+BEGIN_QUOTE
What's a dystopia?
#+END_QUOTE
** #478 Name: ~Anonymous~ :2010/07/28(Wed) 22:09:18
#+BEGIN_QUOTE
How can SERN take over the world in just 20 years?
Look at the middle east. You've been reading too much manga if you think you can get those guys to stop killing each other.
#+END_QUOTE
** #478 Name: ~Anonymous~ :2010/07/28(Wed) 22:11:06
#+BEGIN_QUOTE
Who asked you to change the future? You trying to play God?
If they're promising world peace, then I for one welcome our new SERN overlords.
#+END_QUOTE
** #523 Name: =John Titor= :2010/07/28(Wed) 22:43:19
#+BEGIN_QUOTE
My time machine is a prototype reverse-engineered from stolen SERN technology.
Compared to their time machine, it's capabilities are quite limited.
In 2036, the world is ruled by a single all-powerful governing body.
They administrate every aspect of our lives, deciding what we will eat, where we will live, whom we will marry. There is no privacy and no choice.
Anybody who dares oppose them is eliminated.
There are no trials.
#+END_QUOTE
** #524 Name: ~Anonymous~ :2010/07/28(Wed) 22:44:33
#+BEGIN_QUOTE
in movies and stuff small changes to the past cause huge changes to the future
you've already changed the present by coming here
what happens if you make unexpected changes to the future?
#+END_QUOTE
** #525 Name: ~KuriGohan and Kamehameha~ :2010/07/28(Wed) 20:44:51
#+BEGIN_QUOTE
"implying SERN rules the world"
Do you even know what SERN is? lol
#+END_QUOTE
** #526 Name: ~Anonymous~ :2010/07/28(Wed) 22:45:24
#+BEGIN_QUOTE
OP is a troll
#+END_QUOTE
** #527 Name: ~Anonymous~ :2010/07/28(Wed) 22:46:32
#+BEGIN_QUOTE
so if we find his dad and kill him
then this time traveller (lmao) will never be born and we won't have to listen to this bullshit amirite
#+END_QUOTE
** #528 Name: ~Anonymous~ :2010/07/28(Wed) 22:47:41
#+BEGIN_QUOTE
I want to know if you can meet your past self.
Can you have selfcest?
#+END_QUOTE
** #689 Name: =John Titor= :2010/07/28(Wed) 23:31:58
#+BEGIN_QUOTE
You're talking about the so-called 'Grandfather Paradox.' That has been debunked. This ***world line*** has a divergence of 0.571024% compared to the world line I came from.
Killing my father would alter the divergence, creating a world line where my father is dead.
However, it would not erase this world line. I would go on existing.
SERN is a perticle physics research institution.
That hasn't changed in 2036.
It is possible to meet your past self.
The prevailing theory in my time is that nothing would happen.
I, however, haven't met my past seld.
#+END_QUOTE
** #690 Name: ~Anonymous~ :2010/07/28(Wed) 23:33:10
#+BEGIN_QUOTE
if ur really a time traveller then fucking prove it
post time machine pics or gtfo
#+END_QUOTE
** #691 Name: ~Anonymous~ :2010/07/28(Wed) 23:33:10
#+BEGIN_QUOTE
The many-worlds interpretation? Whoa, slow down bro
#+END_QUOTE
** #692 Name: ~Anonymous~ :2010/07/28(Wed) 23:34:26
#+BEGIN_QUOTE
research institution talking over the world
lolwut
#+END_QUOTE
** #711 Name: =John Titor= :2010/07/28(Wed) 23:49:26
#+BEGIN_QUOTE
I do not feel the need to prove that I am what I say I am.
I am only posting this message on a whim.
My mission comes first.
#+END_QUOTE
** #712 Name: ~Anonymous~ :2010/07/28(Wed) 23:49:45
#+BEGIN_QUOTE
What are world lines?
Can you meet yourself from another world line?
What happens if you do?
#+END_QUOTE
** #713 Name: ~Anonymous~ :2010/07/28(Wed) 23:50:36
#+BEGIN_QUOTE
#476
late reply. A tripcode is a way to identify posters
Put #password after your name
#+END_QUOTE
** #714 Name: ~Anonymous~ :2010/07/28(Wed) 23:51:11
#+BEGIN_QUOTE
lol backpedaling
#+END_QUOTE
** #807 Name:JOHN TITOR#f8VunoyWU :2010/07/29(Thu) 00:50:57
#+BEGIN_QUOTE
World lines are like an infinite number of rivers flowing in parallel. Along the way, they are constantly branching out into new world lines.
This is called divergence.
For example, ehether or not you post this meddage board has practically no effect on this world line's divergence.
But if you were murdered, let's say, then divergence would change.
However, it would only change about 0.000002%, approximately.
A single human being's death is not teribly significant on a global scale.
Wars, disasters, acts of terrorism, and other events that cause widespread death and destruction have a much greater effect on divergence.
Thanks for telling me about tripcodes.
I'll make sure to use this one from now on.
I'm starting to get tired, so let's pick up again tomorrow.
It's been fun talking to everybody.
#+END_QUOTE
