:PROPERTIES:
:ID:       afe20a0a-2ef0-4f4b-99b7-da5ef587b031
:END:
#+title:Chat log no 4
#+filetags: :SteinsGate:ChatLog:
* After-thoughts
* 31/07 from 7:14 to 8:30ish
** =John Titor=
#+BEGIN_QUOTE
Life in 2036 is very different from what it is today. Most people live on farms, growing their own food. All form of commerce and communication are restricted. There is no travel, no internet, no railroad even.
Most people never see another town, let alone a city. Science continues to advance, of course, but the vast majority of people do not benefit from that progress. Technology belongs to those chosen by SERN and the committee of 300. It's very peaceful, at least on the surface. There's none of the conflict you see in this era.
#+END_QUOTE
** Anonymous
#+BEGIN_QUOTE
1. There's no war? How is that possible? How did SERN resolve the situation in the middle east?
2. What have you got against the world peace? Sounds to me like SERN is doing humanity a favor.
3. This Titor guy stole a time machine from SERN, didn't he? He is the bad guy here! Die in a fire, terrorist scum!
#+END_QUOTE
** =John Titor=
#+BEGIN_QUOTE
The world in 2036 is governed by SERN. All nations have disbanded their armies.
To put it simply, civilization has retured to an 18th century level of technology and exists under a communist system of government.
Except now, that system works flawlessly.
Right now, you should be asking yourselves a question as to how that is possible?
How does a system of government that collapsed in the 20th century exist without discontent?
The answer to that question is the reason I am here.
Yes, I'm a terrorist.
There are others like me who fight against SERN.
We think of ourselves as the Resistance, but there is no denying that our actions are a kind of terrorism.
#+END_QUOTE
** Anonymous
#+BEGIN_QUOTE
1. Anyway, I want to hear more about many-worlds interpretation. You said it has been proven by 2036. How?
2. I knew you were a terrorist. How many you have murdered? What if my kids are among them?  Maybe I really should kill your father and protect the future!
3. Stop beating around the bush. Give us answer!
4. You're one of those old men who participated in the student riots, aren't you? Filed your head with a bunch of bullshit and now you can't tell delusions from reality. Am I right?
5. @No. 4 delicious nationalist tears lololololol... @1 SERN probably figured it out. They've got a time machine to experiment with, right?
#+END_QUOTE
** ~Hououin Kyouma~
#+BEGIN_QUOTE
@Anonymous #2
That would make you no better than Titor. If you're willing to face the consequences, then go right ahead.
Titor, question. Did World War 3 take place as scheduled?
Why did you come to this particular time?
Did you find an IBN 5100?
#+END_QUOTE
** Anonymous
#+BEGIN_QUOTE
1. I thought this Titor guy was crazy but this Hououin guy is even crazier. Get a room guys lol.
2. World War 3 (lmao)
3. Isn't there supposed to be IBN 5100 in Akiba?
#+END_QUOTE
** =John Titor=
#+BEGIN_QUOTE
As I have already explained, my goal this time is to change the future. I'm posting here to warn you of what's going to happen. Perhaps convergence will render my efforts meaningless. But even if one person pays attention, that's enough.
@312 (??)
World War 3?
Is that something I said on a different worldline?
I would like to talk to you in private. Please email me when you have time. Of course, if anyone else would like to email me, feel free.
Serious inquiries only, please. All I've been getting is hate mail. Here's my address once more:
john_titor@egweb.ne.jp
#+END_QUOTE
