:PROPERTIES:
:ID:       35af92d5-7fdb-4d30-9f55-00c081bcfbf7
:END:
#+title:Jellyman's Report
#+filetags: :SteinsGate:Keyword:
* After-thoughts


*
* Jellyman's Report # 9
** Subject: Dan Stayski, Age:26, Canadian
** Z Program Stage 4, Date of Experiment: 2004-09-06 T 14:10
** Results: Error. Human is dead. Mismatch.
** (Newspaper clipping is in french.)
** Date on the newspaper says Jan 31, 2001, with location around Pau, France
** *Daru's Machine Translation*: January 31, 2001. Collapsed male corpse discovered in forest outside Pau, France. It's left foor was fused to a tree trunk, and the body had gelified.
* Jellyman's Report # 8
** Subject: Linda Hill, Age:25, British
** Z Program Stage 4, Date of Experiment: 2004-2-15 T 13:45
** Results: Error. Human is dead. Mismatch.
** On October 2, 1972, the gelified body of a woman was discovered on the streets of Dhramapuri in Tamil Nadu, India. There were signs that the body had been run over by a car.
* Jellyman's Report # 7
** Subject: Michael Lang, Age: 37 Germany
** Z Program Stage 4, Date of Experiment: 2002-10-08 T 13:28.
** Results: Error. Human is dead. Mismatch.
** May 24, 1936
** The corpse of what is believed to be gelified human was discovered at the base of Mt. Hiei in Kyoto. It was in damaged state, possibly from having slid down the slope.
* Jellyman's Report # 6
** Subject: Mark Hughes, Age: 30, American
** Z Program Stage 4, Date of Experiment: 2002-08-23 T 12:52
** Results: Error. Human is dead. Mismatch.
** On July 1, 1985, a strange body washed ashore on the coast of Streymoy, Faroe Islands.It appeared to be the body of an adult male, but its flesh was soft like that of a jellyfish. Some of the island's inhabitants believe that it was the body of a merman. The inscription 'SERN' was found near the body's shoulder, but SERN denies any involvement.
